# -*- coding: utf-8 -*-
"""rfdetr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgAkexNdebOO5wn7_p_3p0wUCsHxp6pd
"""

from roboflow import Roboflow
import torch

class RFDETRBase:
    def __init__(self):
        self.model = None

    def load(self, model_path):
        # Load model yang sudah di-training
        self.model = torch.load(model_path)
        self.model.eval()  # Pastikan model dalam mode evaluasi

    def predict(self, image):
        # Implementasikan prediksi menggunakan model
        with torch.no_grad():
            # Asumsi image sudah sesuai dengan input model
            predictions = self.model(image)
        return predictions